### ISSUE TITLE
Consider adding DATE and TIME tags 

### ISSUE THREAD

**Issue by PJKober** [hadynz/obsidian-kindle-plugin#162] opened 2022-06-07 08:12 UTC
Can you consider to adding DATE and TIME tags? 
**Date & Time** is usefully for notes and is available in **My Clipping.txt** .  

exp. 
- Your Highlight at location 722-723 | Added on Monday, 24 February 2020 09:46:29

**Comment by hadynz** [comment] 2022-06-11 07:12
Duplicate of https://github.com/hadynz/obsidian-kindle-plugin/issues/130. Will track this request with the original ticket raised.

**Closed by hadynz** 2022-06-11 07:12 UTC
Labels: enhancement

**Comment by hadynz** [comment] 2022-06-12 02:45
Done. Added your feature request in [1.6.2][1].

If you can let me know if it works as expected in thread, that would be great.

![image](https://user-images.githubusercontent.com/315585/173212080-1238cc5a-66f0-4d79-ad4e-42781919f7b6.png)

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.6.2
