### ISSUE TITLE
change the format of the file name for the note in Obsidian-Enhancement

### ISSUE THREAD

**Issue by OogieM** [hadynz/obsidian-kindle-plugin#78] opened 2021-09-18 13:26 UTC
I'd like the option tocreate the format for the actual note file names according to my own specification. What I want to do is have the title be the following

{{author|replace(' ', '_')}}-{{title|replace(' ', '_')}}-kindle

**Comment by hadynz** [comment] 2021-09-20 10:43
Thanks for raising this suggestion.

As part of bringing highlight syncing to the plugin, I will be bringing in the functionality to choose how you want your note file names to be configured. Will let you know once it is implemented.

**Comment by hadynz** [comment] 2021-10-31 06:33
The latest [v1.0.x][1] has _decoupled_ the name of the file being synced from the plugin's awareness of the book. So you have a new solution in your hands, which is to manually rename a book with your highlights in whatever format you want without worrying that the plugin will lose track of the book. This has been enabled by the plugin now using frontmatter at the top of every book it syncs to identify that it is something the plugin should track.

I plan to introduce the feature that you ask for — allowing you to specify a naming pattern, so will leave this issue open for the time being. But at least now you are aware that there is a workaround today that you can start using.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.0.0

**Comment by hadynz** [comment] 2021-11-15 07:42
Thanks for your patience. I have implemented your feature request in version [1.3.0][1]. Check it out and let me know if it is working as you expected. 

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.3.0

**Comment by ostraat** [comment] 2021-11-15 12:40
This feature is useful for me, too.  Thanks for implementing it!

One small observation I didn't expect: the file title ends with '.md'.  In other words, the actual system file name ends with '.md.md'.  This occurs whether or the 'File name template' is changed from the default.

**Comment by hadynz** [comment] 2021-11-15 15:58
Oh! That's a bug for sure. I'll make a fix to ensure the .md is always added once.

**Comment by hadynz** [comment] 2021-11-16 10:44
@ostraat This has been fixed in [1.4.0][1]. Please give it a try and let me know if it has resolved this issue for you.

[1]: https://github.com/hadynz/obsidian-kindle-plugin/releases/tag/1.4.0

**Comment by ostraat** [comment] 2021-11-16 13:19
Yes, the issue is resolved for me.  Thanks!

**Closed** 2021-11-18 17:18 UTC
Labels: enhancement
