### ISSUE TITLE
Can't sync all the highlights in some books 

### ISSUE THREAD

**Issue by Ottavi** [hadynz/obsidian-kindle-plugin#143] opened 2022-02-18 17:00 UTC
this is a great plugin that really changes my reading habit, but some books cannot be synced completely. for example:

<img width="960" alt="屏幕截图 2022-02-19 005524" src="https://user-images.githubusercontent.com/85220473/154727555-f91262fa-f76c-4ec1-979a-be533c3e0635.png">

these yellow highlights are all from the same book, but in obsidian, there is only one of them.

<img width="960" alt="屏幕截图 2022-02-19 005553" src="https://user-images.githubusercontent.com/85220473/154727791-471461e2-a219-4663-9380-cb967567fed6.png">

(forgive my broken English

**Comment by hadynz** [comment] 2022-05-20 07:44
I believe this is a duplicate of https://github.com/hadynz/obsidian-kindle-plugin/issues/145:

- Occurs when you sync using the My Clippings.txt file
- Highlights are missing when you have another highlight on the same page. The plugin incorrectly was handling duplicates

Please try the fix that has been made and re-open this issue if you still think it has not been resolved.

**Closed by hadynz** 2022-05-20 07:44 UTC
